name: RobinDavisNZ
favicon: null
layout_spectrum: 0.2297029651235789
typography_spectrum: 0.15087005030363798
title: Design // Illustration // Retouching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfde1'
    - '#c7c3aa'
    - '#101130'
    - '#888886'
    - '#5c5b60'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
